Repository WomenWhoCode/WWCodeGreenville, pull requests merged in 2023-11, with the labels that each got.

#134 Add API test to make sure status is a known value to us.
  HackGreenvilleEventsAPITestSuite/EventsAPI.json
Labels: Postman Events API Test Suite

#133 Post-Hacktoberfest updates
  README.md
Labels: documentation, Hacktoberfest, maintenance

#128 Add back to top button
  Gettingstarted.md
  README.md
Labels: documentation
